### ISSUE TITLE
`yaplon`, because I hate .plist :) 

### ISSUE THREAD

**Issue by twardoch** [daltonmaag/statmake#7]
I’ve written a small commandline tool [`yaplon`](https://pypi.org/project/yaplon/) that comes with a CLI command `yaml22plist`, because I truly hate writing .plist (including .stylespace) by hand. 

So now I can write my stylespace like this:

```yaml
{axes: [{name: Weight, tag: wght, locations: [{name: Hairline, value: 100}, {name: Thin,
          value: 200}, {name: Light, value: 300}, {name: Regular, value: 400, linked_value: 700,
          flags: [ElidableAxisValueName]}, {name: Medium, value: 500}, {name: Semibold,
          value: 600}, {name: Bold, value: 700}, {name: Heavy, value: 800}, {name: Black,
          value: 900}]}, {name: Italic, tag: ital, locations: [{name: Upright, value: 0,
          linked_value: 1, flags: [ElidableAxisValueName]}]}]}
```

or this:

```yaml
axes:
-   name: Weight
    tag: wght
    locations:
    -   name: Hairline
        value: 100
    -   name: Thin
        value: 200
    -   name: Light
        value: 300
    -   name: Regular
        value: 400
        linked_value: 700
        flags:
        - ElidableAxisValueName
    -   name: Medium
        value: 500
    -   name: Semibold
        value: 600
    -   name: Bold
        value: 700
    -   name: Heavy
        value: 800
    -   name: Black
        value: 900
-   name: Italic
    tag: ital
    locations:
    -   name: Upright
        value: 0
        linked_value: 1
        flags:
        - ElidableAxisValueName
```

and via `yaml2plist -i Lato.stylespace.yaml -o Lato.stylespace`, I get

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>axes</key>
        <array>
            <dict>
                <key>name</key>
                <string>Weight</string>
                <key>tag</key>
                <string>wght</string>
                <key>locations</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>Hairline</string>
                        <key>value</key>
                        <integer>100</integer>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Thin</string>
                        <key>value</key>
                        <integer>200</integer>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Light</string>
                        <key>value</key>
                        <integer>300</integer>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Regular</string>
                        <key>value</key>
                        <integer>400</integer>
                        <key>linked_value</key>
                        <integer>700</integer>
                        <key>flags</key>
                        <array>
                            <string>ElidableAxisValueName</string>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Medium</string>
                        <key>value</key>
                        <integer>500</integer>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Semibold</string>
                        <key>value</key>
                        <integer>600</integer>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Bold</string>
                        <key>value</key>
                        <integer>700</integer>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Heavy</string>
                        <key>value</key>
                        <integer>800</integer>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>Black</string>
                        <key>value</key>
                        <integer>900</integer>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>name</key>
                <string>Italic</string>
                <key>tag</key>
                <string>ital</string>
                <key>locations</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>Upright</string>
                        <key>value</key>
                        <integer>0</integer>
                        <key>linked_value</key>
                        <integer>1</integer>
                        <key>flags</key>
                        <array>
                            <string>ElidableAxisValueName</string>
                        </array>
                    </dict>
                </array>
            </dict>
        </array>
    </dict>
</plist>
```

**Comment by twardoch** [comment]
And [`Test.stylespace`](https://github.com/daltonmaag/statmake/blob/master/tests/data/Test.stylespace) in YAML is:

```yaml
axes:
-   name: Weight
    tag: wght
    locations:
    -   name: XLight
        value: 200
    -   name: Light
        value: 300
    -   name:
            en: Regular
            de: Regulär
        value: 400
        linked_value: 700
        flags:
        - ElidableAxisValueName
    -   name: Semi Bold
        value: 600
    -   name:
            en: Bold
        value: 700
    -   name: Black
        value: 900
        range:
        - 701
        - 900
-   name: Italic
    tag: ital
    locations:
    -   name: Upright
        value: 0
        linked_value: 1
        flags:
        - ElidableAxisValueName
    -   name: Italic
        value: 1
locations:
-   name: ASDF
    axis_values:
        Weight: 333
        Italic: 1
-   name: fgfg
    axis_values:
        Weight: 650
        Italic: 0.5
    flags:
    - ElidableAxisValueName
```

(You can of course have comments there.)
